/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteControlador;
import Modelo.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zakkc
 */
public class ClienteForm extends javax.swing.JInternalFrame {

    private ClienteControlador controlador = new ClienteControlador();
    private DefaultTableModel modeloTabla;
    private boolean modoEdicion = false;

    /**
     * Creates new form ClienteForm
     */
    public ClienteForm() {
        initComponents();
        configurarTabla();
        setFormularioHabilitado(false);
        cargarTabla();
        
        // Vincular comportamiento dinámico del check de alergias
        txtDetalleAlergia.setEnabled(false);
        chkAlergia.addActionListener(e -> txtDetalleAlergia.setEnabled(chkAlergia.isSelected()));
        
        // Configurar botones
        btnNuevo.addActionListener(e -> btnNuevoActionPerformed());
        btnGuardar.addActionListener(e -> btnGuardarActionPerformed());
        btnEditar.addActionListener(e -> btnEditarActionPerformed());
        jButton1.addActionListener(e -> btnEliminarActionPerformed());
        btnLimpiar.addActionListener(e -> btnLimpiarActionPerformed());
        btnBuscar.addActionListener(e -> btnBuscarActionPerformed());
        restringirCaracteresVisuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkAlergia = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtDetalleAlergia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSeguro = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Codigo");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Nombre");

        jLabel5.setText("DNI");

        jLabel6.setText("Correo");

        chkAlergia.setText("Alergias");

        jLabel7.setText("Alergia Detalle:");

        jLabel8.setText("Seguro Medico");

        txtApellidoMaterno.addActionListener(this::txtApellidoMaternoActionPerformed);

        btnNuevo.setText("Nuevo");

        btnGuardar.setText("Guardar");

        btnEditar.setText("Editar");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAlergia)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(txtDetalleAlergia)
                            .addComponent(txtCodigo)
                            .addComponent(txtApellidoPaterno)
                            .addComponent(txtApellidoMaterno)
                            .addComponent(txtNombre)
                            .addComponent(txtDni)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(txtSeguro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton1)
                                .addGap(23, 23, 23)
                                .addComponent(btnLimpiar)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAlergia)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDetalleAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnLimpiar))
                .addGap(33, 33, 33))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Buscar");

        btnBuscar.setText("Buscar Código");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new String[]{"Código", "Nombre", "Ap. Paterno", "Ap. Materno", "DNI", "Correo", "Alergias", "Seguro"}, 0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblClientes.setModel(modeloTabla);
        tblClientes.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) cargarSeleccion();
        });
    }

    private void cargarTabla() {
        modeloTabla.setRowCount(0);
        ArrayList<Cliente> lista = controlador.listarTodos();
        for (Cliente c : lista) {
            String[] apellidos = c.getApellido().split(" ", 2);
            String paterno = apellidos.length > 0 ? apellidos[0] : "";
            String materno = apellidos.length > 1 ? apellidos[1] : "";
            modeloTabla.addRow(new Object[]{
                c.getCodigo(),
                c.getNombre(),
                paterno,
                materno,
                c.getDni(),
                c.getCorreo(),
                c.verificarAlergia() ? c.getDetalleAlergia() : "No",
                c.getSeguroMedico()
            });
        }
    }

    private void cargarSeleccion() {
        int fila = tblClientes.getSelectedRow();
        if (fila < 0) return;
        String codigo = (String) modeloTabla.getValueAt(fila, 0);
        Cliente c = controlador.buscarPorCodigo(codigo);
        if (c == null) return;

        txtCodigo.setText(c.getCodigo());
        txtNombre.setText(c.getNombre());
        
        String[] apellidos = c.getApellido().split(" ", 2);
        txtApellidoPaterno.setText(apellidos.length > 0 ? apellidos[0] : "");
        txtApellidoMaterno.setText(apellidos.length > 1 ? apellidos[1] : "");
        
        txtDni.setText(c.getDni());
        txtCorreo.setText(c.getCorreo());
        chkAlergia.setSelected(c.verificarAlergia());
        txtDetalleAlergia.setText(c.getDetalleAlergia());
        txtDetalleAlergia.setEnabled(c.verificarAlergia());
        txtSeguro.setText(c.getSeguroMedico());
    }

    private void setFormularioHabilitado(boolean b) {
        txtCodigo.setEnabled(b && !modoEdicion);
        txtNombre.setEnabled(b);
        txtApellidoPaterno.setEnabled(b);
        txtApellidoMaterno.setEnabled(b);
        txtDni.setEnabled(b);
        txtCorreo.setEnabled(b);
        chkAlergia.setEnabled(b);
        txtDetalleAlergia.setEnabled(b && chkAlergia.isSelected());
        txtSeguro.setEnabled(b);
        btnGuardar.setEnabled(b);
    }

    private void limpiarFormulario() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtDni.setText("");
        txtCorreo.setText("");
        chkAlergia.setSelected(false);
        txtDetalleAlergia.setText("");
        txtDetalleAlergia.setEnabled(false);
        txtSeguro.setText("");
        modoEdicion = false;
    }

    private void btnNuevoActionPerformed() {
        limpiarFormulario();
        modoEdicion = false;
        setFormularioHabilitado(true);
        txtCodigo.requestFocus();
    }

    private void btnGuardarActionPerformed() {
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apPaterno = txtApellidoPaterno.getText().trim();
        String apMaterno = txtApellidoMaterno.getText().trim();
        String dni = txtDni.getText().trim();
        String correo = txtCorreo.getText().trim();
        boolean alergia = chkAlergia.isSelected();
        String detAlergia = txtDetalleAlergia.getText().trim();
        String seguro = txtSeguro.getText().trim();

        if (codigo.isEmpty() || nombre.isEmpty() || apPaterno.isEmpty() || apMaterno.isEmpty() || dni.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Código, Nombre, Apellidos, DNI y Correo) son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String apellidoCompleto = apPaterno + " " + apMaterno;
        String resultado;

        if (!modoEdicion) {
            resultado = controlador.registrar(codigo, nombre, apellidoCompleto, dni, correo, alergia, detAlergia, seguro);
        } else {
            resultado = controlador.actualizar(codigo, nombre, apellidoCompleto, dni, correo, alergia, detAlergia, seguro);
        }

        if (resultado.equals("ok")) {
            JOptionPane.showMessageDialog(this, modoEdicion ? "✅ Cliente actualizado." : "✅ Cliente registrado.");
            limpiarFormulario();
            setFormularioHabilitado(false);
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnEditarActionPerformed() {
        int fila = tblClientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla para editar.", "Editar Cliente", JOptionPane.WARNING_MESSAGE);
            return;
        }
        modoEdicion = true;
        setFormularioHabilitado(true);
        txtNombre.requestFocus();
    }

    private void btnEliminarActionPerformed() {
        int fila = tblClientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla para eliminar.", "Eliminar Cliente", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigo = (String) modeloTabla.getValueAt(fila, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar a este cliente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String resultado = controlador.eliminar(codigo);
            if (resultado.equals("ok")) {
                JOptionPane.showMessageDialog(this, "✅ Cliente eliminado.");
                limpiarFormulario();
                setFormularioHabilitado(false);
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnLimpiarActionPerformed() {
        limpiarFormulario();
        setFormularioHabilitado(false);
        cargarTabla();
    }

    private void btnBuscarActionPerformed() {
        String query = txtBuscar.getText().trim();
        if (query.isEmpty()) {
            cargarTabla();
            return;
        }

        Cliente c = controlador.buscarPorCodigo(query);
        modeloTabla.setRowCount(0);
        if (c != null) {
            String[] apellidos = c.getApellido().split(" ", 2);
            String paterno = apellidos.length > 0 ? apellidos[0] : "";
            String materno = apellidos.length > 1 ? apellidos[1] : "";
            modeloTabla.addRow(new Object[]{
                c.getCodigo(),
                c.getNombre(),
                paterno,
                materno,
                c.getDni(),
                c.getCorreo(),
                c.verificarAlergia() ? c.getDetalleAlergia() : "No",
                c.getSeguroMedico()
            });
        }
    }

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    }


    private void restringirCaracteresVisuales() {
        java.awt.event.KeyAdapter soloLetras = new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isLetter(c) && c != ' ') {
                    evt.consume();
                }
            }
        };

        if (txtNombre != null) txtNombre.addKeyListener(soloLetras);
        if (txtApellidoPaterno != null) txtApellidoPaterno.addKeyListener(soloLetras);
        if (txtApellidoMaterno != null) txtApellidoMaterno.addKeyListener(soloLetras);

        if (txtDni != null) {
            txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    char c = evt.getKeyChar();
                    String text = txtDni.getText();
                    if (!Character.isLetterOrDigit(c) || text.length() >= 11) {
                        evt.consume();
                    }
                }
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkAlergia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDetalleAlergia;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeguro;
    // End of variables declaration//GEN-END:variables
}
