/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CompraControlador;
import Modelo.Compra;
import Modelo.Medicamento;
import Modelo.Proveedor;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zakkc
 */
public class CompraForm extends javax.swing.JInternalFrame {

    private CompraControlador controlador = new CompraControlador();
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form CompraForm
     */
    public CompraForm() {
        initComponents();
        configurarTabla();
        cargarCombos();
        cargarTabla();
        
        // Registrar listeners de eventos
        btnRegistrar.addActionListener(e -> btnRegistrarActionPerformed());
        btnRecibirMercadería.addActionListener(e -> btnRecibirActionPerformed());
        
        // Restricciones de teclado directas (UX)
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                String text = txtTotal.getText();
                if (!Character.isDigit(c) && c != '.') {
                    evt.consume();
                }
                if (c == '.' && text.contains(".")) {
                    evt.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbMedicamento = new javax.swing.JComboBox<>();
        cmbProveedor = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnRecibirMercadería = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Medicamento");

        jLabel2.setText("Proveedor");

        jLabel3.setText("Cantidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jLabel4.setText("Total Pagado");

        cmbMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Estado de Compra");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompras);

        btnRegistrar.setText("Registrar");

        btnRecibirMercadería.setText("Recibir Mercadería");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(btnRegistrar)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRecibirMercadería)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal)
                            .addComponent(cmbEstado, 0, 204, Short.MAX_VALUE)
                            .addComponent(cmbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad)
                            .addComponent(cmbMedicamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnRecibirMercadería))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new String[]{"ID Compra", "Fecha", "Medicamento", "Proveedor", "Cantidad", "Total Pagado", "Estado"}, 0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblCompras.setModel(modeloTabla);
    }

    private void cargarCombos() {
        cmbMedicamento.removeAllItems();
        for (Medicamento m : new Controlador.MedicamentoControlador().listarTodos()) {
            cmbMedicamento.addItem(m.getCodigo() + " - " + m.getNombre());
        }

        cmbProveedor.removeAllItems();
        for (Proveedor p : new Controlador.ProveedorControlador().listarTodos()) {
            cmbProveedor.addItem(p.getCodigo() + " - " + p.getNombre());
        }

        cmbEstado.removeAllItems();
        cmbEstado.addItem("Pendiente");
        cmbEstado.addItem("Recibida");
    }

    private void cargarTabla() {
        modeloTabla.setRowCount(0);
        for (Compra c : controlador.listarTodas()) {
            Medicamento m = Medicamento.buscarPorID(c.getCodigoMedicamento());
            Proveedor p = new Datos.ProveedorDatos().buscarPorCodigo(c.getIdProveedor());
            String nombreMed = (m != null) ? m.getNombre() : c.getCodigoMedicamento();
            String nombreProv = (p != null) ? p.getNombre() : c.getIdProveedor();

            modeloTabla.addRow(new Object[]{
                c.getIDcompra(),
                c.getFechaCompra(),
                nombreMed,
                nombreProv,
                c.getCantidadComprada(),
                String.format("S/ %.2f", c.getTotalPagado()),
                c.getEstadoOrden()
            });
        }
    }

    private void btnRegistrarActionPerformed() {
        String itemMed = (String) cmbMedicamento.getSelectedItem();
        String itemProv = (String) cmbProveedor.getSelectedItem();
        
        if (itemMed == null || itemProv == null) {
            JOptionPane.showMessageDialog(this, "Debe registrar proveedores y medicamentos antes de comprar.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoMed = itemMed.split(" - ")[0];
        String idProv = itemProv.split(" - ")[0];
        
        String cantidad = txtCantidad.getText().trim();
        String total = txtTotal.getText().trim();
        String estado = (String) cmbEstado.getSelectedItem();
        
        String idCompra = controlador.generarNuevoID();
        String fecha = new SimpleDateFormat("dd/MM/yyyy").format(new Date());

        String resultado = controlador.registrar(idCompra, fecha, total, estado, cantidad, idProv, codigoMed);
        if (resultado.equals("ok")) {
            JOptionPane.showMessageDialog(this, "✅ Compra " + idCompra + " registrada correctamente.");
            txtCantidad.setText("");
            txtTotal.setText("");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnRecibirActionPerformed() {
        int fila = tblCompras.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una compra de la tabla para recibir mercadería.", "Recibir Mercadería", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idCompra = (String) modeloTabla.getValueAt(fila, 0);
        String resultado = controlador.recibirMercaderia(idCompra);
        if (resultado.equals("ok")) {
            JOptionPane.showMessageDialog(this, "✅ Mercadería recibida. El stock del medicamento ha sido incrementado.");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecibirMercadería;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMedicamento;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
