/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteControlador;
import Controlador.MedicamentoControlador;
import Controlador.VentaControlador;
import Modelo.Medicamento;
import Modelo.Venta;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author zakkc
 */
public class DashboardForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        setClosable(true); // Permite cerrar el JInternalFrame
        inicializarDashboard(); // Inicializa los datos y el gráfico del Dashboard
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblVentasDia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblClientesRegistrados = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblStockBajoAlertas = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblProductosVencer = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<>();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        btnAplicarRango = new javax.swing.JButton();
        lblPeriodoActivo = new javax.swing.JLabel();
        panelGrafico = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(202, 126, 16));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentasDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentasDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(151, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientesRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientesRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStockBajoAlertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStockBajoAlertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(246, 178, 107));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductosVencer, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductosVencer, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo.addActionListener(this::cmbPeriodoActionPerformed);

        btnAplicarRango.setText("Aplicar");

        lblPeriodoActivo.setForeground(new java.awt.Color(255, 255, 255));

        panelGrafico.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelGrafico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPeriodoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAplicarRango, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(lblPeriodoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAplicarRango))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeriodoActionPerformed
        // Manejado por el listener agregado programáticamente en inicializarDashboard()
    }//GEN-LAST:event_cmbPeriodoActionPerformed


    private void inicializarDashboard() {

        // --- CONFIGURAR ITEMS DEL COMBOBOX DE PERÍODO ---
        cmbPeriodo.removeAllItems();
        cmbPeriodo.addItem("Hoy");
        cmbPeriodo.addItem("Ayer");
        cmbPeriodo.addItem("Últimos 7 días");
        cmbPeriodo.addItem("Este mes");
        cmbPeriodo.addItem("Mes anterior");
        cmbPeriodo.addItem("Rango personalizado");
        cmbPeriodo.setSelectedItem("Últimos 7 días"); // Selección por defecto

        // Deshabilitar controles de rango personalizado al inicio (no ocultar para evitar deformar el layout)
        dcFechaInicio.setEnabled(false);
        dcFechaFin.setEnabled(false);
        btnAplicarRango.setEnabled(false);

        // Actualizar evento del ComboBox para habilitar/deshabilitar controles de rango
        cmbPeriodo.removeActionListener(null);
        cmbPeriodo.addActionListener(e -> {
            String sel = (String) cmbPeriodo.getSelectedItem();
            boolean esRango = "Rango personalizado".equals(sel);
            dcFechaInicio.setEnabled(esRango);
            dcFechaFin.setEnabled(esRango);
            btnAplicarRango.setEnabled(esRango);
            if (!esRango) aplicarFiltro(sel);
        });

        // Evento botón Aplicar rango personalizado
        btnAplicarRango.addActionListener(e -> {
            Date desde = dcFechaInicio.getDate();
            Date hasta = dcFechaFin.getDate();
            if (desde == null || hasta == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "⚠ Seleccione ambas fechas.", "Rango incompleto", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (desde.after(hasta)) {
                javax.swing.JOptionPane.showMessageDialog(this, "⚠ La fecha de inicio no puede ser mayor que la fecha final.", "Rango inválido", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            String etiqueta = "Rango: " + sdf.format(desde) + " → " + sdf.format(hasta);
            actualizarTarjetas(desde, hasta);
            actualizarGrafico(desde, hasta, etiqueta);
            lblPeriodoActivo.setText("📅 Mostrando: " + etiqueta);
        });

        // --- DATOS ESTÁTICOS (no cambian con el período) ---
        ClienteControlador ctrlCliente = new ClienteControlador();
        MedicamentoControlador ctrlMedicamento = new MedicamentoControlador();

        int cantClientes = ctrlCliente.listarTodos().size();
        lblClientesRegistrados.setText("<html><center><font size='4' color='#555555'><b>Clientes Registrados</b></font><br><br><font size='6' color='#1565c0'><b>" + cantClientes + "</b></font></center></html>");
        lblClientesRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        int alertasStock = 0;
        for (Medicamento m : ctrlMedicamento.listarTodos()) {
            if (m.stockBajo()) alertasStock++;
        }
        lblStockBajoAlertas.setText("<html><center><font size='4' color='#555555'><b>Alertas de Stock Bajo</b></font><br><br><font size='6' color='#c62828'><b>" + alertasStock + "</b></font></center></html>");
        lblStockBajoAlertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        int proximosVencer = ctrlMedicamento.contarProximosVencer();
        lblProductosVencer.setText("<html><center><font size='4' color='#555555'><b>Próximos a Vencer</b></font><br><br><font size='6' color='#d84315'><b>" + proximosVencer + "</b></font></center></html>");
        lblProductosVencer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Cargar período por defecto
        aplicarFiltro("Últimos 7 días");
    }


    /**
     * Calcula el rango de fechas según la opción del ComboBox y delega
     * la actualización al gráfico y a las tarjetas dinámicas.
     */
    private void aplicarFiltro(String opcion) {
        Calendar cal = Calendar.getInstance();
        Date hasta = cal.getTime(); // Por defecto: hoy
        Date desde;
        String etiqueta;

        switch (opcion) {
            case "Hoy":
                desde = truncarHora(cal.getTime());
                hasta = desde;
                etiqueta = "Hoy";
                break;
            case "Ayer":
                cal.add(Calendar.DAY_OF_YEAR, -1);
                desde = truncarHora(cal.getTime());
                hasta = desde;
                etiqueta = "Ayer";
                break;
            case "Este mes":
                cal.set(Calendar.DAY_OF_MONTH, 1);
                desde = truncarHora(cal.getTime());
                hasta = new Date();
                etiqueta = "Este mes";
                break;
            case "Mes anterior":
                cal.add(Calendar.MONTH, -1);
                cal.set(Calendar.DAY_OF_MONTH, 1);
                desde = truncarHora(cal.getTime());
                cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
                hasta = truncarHora(cal.getTime());
                etiqueta = "Mes anterior";
                break;
            default: // Últimos 7 días
                cal.add(Calendar.DAY_OF_YEAR, -6);
                desde = truncarHora(cal.getTime());
                hasta = new Date();
                etiqueta = "Últimos 7 días";
                break;
        }

        actualizarTarjetas(desde, hasta);
        actualizarGrafico(desde, hasta, etiqueta);
        lblPeriodoActivo.setText("📅 Mostrando: " + etiqueta);
    }

    /**
     * Actualiza la tarjeta de "Ventas del período" sumando las ventas
     * cuya fecha está dentro del rango [desde, hasta].
     */
    private void actualizarTarjetas(Date desde, Date hasta) {
        VentaControlador ctrlVenta = new VentaControlador();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        double totalPeriodo = 0.0;

        for (Venta v : ctrlVenta.listarTodas()) {
            try {
                Date fechaVenta = sdf.parse(v.getFechaVenta());
                if (!fechaVenta.before(truncarHora(desde)) && !fechaVenta.after(truncarHora(hasta))) {
                    totalPeriodo += v.getTotal();
                }
            } catch (ParseException ignored) {}
        }

        lblVentasDia.setText("<html><center><font size='4' color='#555555'><b>Ventas del Período</b></font><br><br><font size='6' color='#2e7d32'><b>S/ " + String.format("%.2f", totalPeriodo) + "</b></font></center></html>");
        lblVentasDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    /**
     * Regenera el gráfico de barras mostrando los días del rango seleccionado.
     * Si el rango supera los 31 días, agrupa por semana para mayor legibilidad.
     */
    private void actualizarGrafico(Date desde, Date hasta, String tituloExtra) {
        VentaControlador ctrlVenta = new VentaControlador();
        SimpleDateFormat sdfCompleto = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdfEtiqueta = new SimpleDateFormat("dd/MM");

        // Construir mapa fecha → total vendido
        HashMap<String, Double> ventasPorFecha = new HashMap<>();
        for (Venta v : ctrlVenta.listarTodas()) {
            ventasPorFecha.merge(v.getFechaVenta(), v.getTotal(), Double::sum);
        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        long diffMs = hasta.getTime() - desde.getTime();
        long diffDias = diffMs / (1000 * 60 * 60 * 24) + 1;

        Calendar cur = Calendar.getInstance();
        cur.setTime(truncarHora(desde));

        if (diffDias <= 31) {
            // Modo día a día
            while (!cur.getTime().after(truncarHora(hasta))) {
                String clave = sdfCompleto.format(cur.getTime());
                String etiq  = sdfEtiqueta.format(cur.getTime());
                dataset.addValue(ventasPorFecha.getOrDefault(clave, 0.0), "Ventas", etiq);
                cur.add(Calendar.DAY_OF_YEAR, 1);
            }
        } else {
            // Modo semanal: agrupar cada 7 días
            SimpleDateFormat sdfSem = new SimpleDateFormat("'Sem' W/MM");
            while (!cur.getTime().after(truncarHora(hasta))) {
                double totalSemana = 0.0;
                String etiqSem = sdfSem.format(cur.getTime());
                for (int d = 0; d < 7; d++) {
                    String clave = sdfCompleto.format(cur.getTime());
                    totalSemana += ventasPorFecha.getOrDefault(clave, 0.0);
                    cur.add(Calendar.DAY_OF_YEAR, 1);
                    if (cur.getTime().after(truncarHora(hasta))) break;
                }
                dataset.addValue(totalSemana, "Ventas", etiqSem);
            }
        }

        // Crear y personalizar el gráfico
        JFreeChart chart = ChartFactory.createBarChart(
            "Ventas — " + tituloExtra,
            "Período",
            "Monto (S/)",
            dataset,
            PlotOrientation.VERTICAL,
            false, true, false
        );
        chart.setBackgroundPaint(Color.WHITE);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(new Color(245, 245, 245));
        plot.setDomainGridlinePaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.LIGHT_GRAY);
        
        // Evitar números microscópicos (E-9) cuando todo es 0
        org.jfree.chart.axis.NumberAxis rangeAxis = (org.jfree.chart.axis.NumberAxis) plot.getRangeAxis();
        rangeAxis.setAutoRangeIncludesZero(true);
        // rangeAxis.setLowerBound(0.0); // opcional, pero con setAutoRangeIncludesZero basta
        
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new Color(202, 126, 16));
        renderer.setMaximumBarWidth(0.35);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBackground(Color.WHITE);
        
        // ¡CRUCIAL PARA NETBEANS! Conservar el tamaño original de panelGrafico
        // para que ChartPanel no lo encoja ni deforme el diseño de GroupLayout
        java.awt.Dimension dimOriginal = panelGrafico.getPreferredSize();
        chartPanel.setPreferredSize(dimOriginal);

        panelGrafico.setLayout(new BorderLayout());
        panelGrafico.removeAll();
        panelGrafico.add(chartPanel, BorderLayout.CENTER);
        panelGrafico.revalidate();
        panelGrafico.repaint();
    }

    /** Elimina la hora de una fecha dejando solo año/mes/día a las 00:00:00 */
    private Date truncarHora(Date fecha) {
        Calendar c = Calendar.getInstance();
        c.setTime(fecha);
        c.set(Calendar.HOUR_OF_DAY, 0);
        c.set(Calendar.MINUTE, 0);
        c.set(Calendar.SECOND, 0);
        c.set(Calendar.MILLISECOND, 0);
        return c.getTime();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarRango;
    private javax.swing.JComboBox<String> cmbPeriodo;
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblClientesRegistrados;
    private javax.swing.JLabel lblPeriodoActivo;
    private javax.swing.JLabel lblProductosVencer;
    private javax.swing.JLabel lblStockBajoAlertas;
    private javax.swing.JLabel lblVentasDia;
    private javax.swing.JPanel panelGrafico;
    // End of variables declaration//GEN-END:variables
}
