/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author zakkc
 */
public class Escritorio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Escritorio.class.getName());

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        //this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        configurarSegunRol();
        actualizarStatusBar();
        agregarMenuClientes();
        agregarMenuCompras();
    }
    
    private void configurarSegunRol() {
    // Ocultar Usuarios si no es Titular Gerente
    mUsuarios.setVisible(Controlador.SesionControlador.esTitularGerente());
    }
    
    private void actualizarStatusBar() {
    Modelo.Usuario u = Controlador.SesionControlador.getUsuarioActivo();
    jLabel1.setText("👤 " + u.getNombre() + "  |  🛡 " + u.getRol());

    Controlador.MedicamentoControlador mc = new Controlador.MedicamentoControlador();
    int alertas = mc.contarProximosVencer();
    if (alertas > 0) {
        jLabel2.setText("⚠ " + alertas + " medicamentos próximos a vencer");
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
    } else {
        jLabel2.setText("✅ Sin alertas de vencimiento");
        jLabel2.setForeground(new java.awt.Color(100, 200, 100));
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEscritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        mMedicamentos = new javax.swing.JMenu();
        mVentas = new javax.swing.JMenu();
        mReportes = new javax.swing.JMenu();
        mProveedores = new javax.swing.JMenu();
        mUsuarios = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        pEscritorio.setBackground(new java.awt.Color(232, 237, 242));

        jPanel1.setBackground(new java.awt.Color(26, 42, 58));

        jLabel1.setForeground(new java.awt.Color(204, 231, 234));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(204, 231, 234));
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        pEscritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pEscritorioLayout = new javax.swing.GroupLayout(pEscritorio);
        pEscritorio.setLayout(pEscritorioLayout);
        pEscritorioLayout.setHorizontalGroup(
            pEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pEscritorioLayout.setVerticalGroup(
            pEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEscritorioLayout.createSequentialGroup()
                .addGap(0, 429, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pEscritorio, java.awt.BorderLayout.CENTER);

        mbMenu.setBackground(new java.awt.Color(26, 82, 118));
        mbMenu.setForeground(new java.awt.Color(255, 255, 255));
        mbMenu.setOpaque(true);

        mMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        mMedicamentos.setText("💊  Medicamentos");
        mMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMedicamentosMouseClicked(evt);
            }
        });
        mbMenu.add(mMedicamentos);

        mVentas.setForeground(new java.awt.Color(255, 255, 255));
        mVentas.setText("🛒 Ventas");
        mVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVentasMouseClicked(evt);
            }
        });
        mbMenu.add(mVentas);

        mReportes.setForeground(new java.awt.Color(255, 255, 255));
        mReportes.setText("📊 Reportes");
        mReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mReportesMouseClicked(evt);
            }
        });
        mbMenu.add(mReportes);

        mProveedores.setForeground(new java.awt.Color(255, 255, 255));
        mProveedores.setText("🚚 Proveedores");
        mProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mProveedoresMouseClicked(evt);
            }
        });
        mbMenu.add(mProveedores);

        mUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        mUsuarios.setText("👥 Usuarios");
        mUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mUsuariosMouseClicked(evt);
            }
        });
        mbMenu.add(mUsuarios);

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("🚪 Cerrar Sesión");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        mbMenu.add(jMenu1);

        setJMenuBar(mbMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //-------------------------------------METODOS PARA LLAMAR A LAS VENTANAS :)
    private void abrirVentana(javax.swing.JInternalFrame ventana) 
    {
        for (javax.swing.JInternalFrame v : pEscritorio.getAllFrames()) 
        {
            if (v.getClass() == ventana.getClass()) 
            {
                v.toFront();
                try { v.setSelected(true); } catch (Exception e) {}
                return;
            }
        }
    pEscritorio.add(ventana);
    ventana.setVisible(true);
    }
    
    
    //---------------------------------------------------------------------------
    private void mMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMedicamentosMouseClicked
        
        abrirVentana(new Medicamentos());       // TODO add your handling code here:
    }//GEN-LAST:event_mMedicamentosMouseClicked

    private void mVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVentasMouseClicked
        // TODO add your handling code here:
        abrirVentana(new VentaForm());
    }//GEN-LAST:event_mVentasMouseClicked

    private void mReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mReportesMouseClicked
        abrirVentana(new ReporteForm());       // TODO add your handling code here:
    }//GEN-LAST:event_mReportesMouseClicked

    private void mProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mProveedoresMouseClicked
        // TODO add your handling code here:
        abrirVentana(new proveedorForm());
    }//GEN-LAST:event_mProveedoresMouseClicked

    private void mUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mUsuariosMouseClicked
        if (!Controlador.SesionControlador.esTitularGerente())
        {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Acceso denegado. Solo el Titular Gerente puede gestionar usuarios.",
            "Sin permiso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
        }
        abrirVentana(new Usuarioform());
    }//GEN-LAST:event_mUsuariosMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea cerrar sesión?", "Cerrar Sesión", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) 
        {
            Controlador.SesionControlador.cerrarSesion();
            new Vista.login().setVisible(true); // Abre la pantalla de Login
            this.dispose(); // Cierra el Escritorio actual
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void agregarMenuClientes() {
        javax.swing.JMenu mClientes = new javax.swing.JMenu("👥 Clientes");
        mClientes.setForeground(new java.awt.Color(255, 255, 255));
        mClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentana(new ClienteForm());
            }
        });
        int index = mbMenu.getComponentIndex(jMenu1);
        if (index >= 0) {
            mbMenu.add(mClientes, index);
        } else {
            mbMenu.add(mClientes);
        }
        mbMenu.revalidate();
    }

    private void agregarMenuCompras() {
        javax.swing.JMenu mCompras = new javax.swing.JMenu("🛒 Compras");
        mCompras.setForeground(new java.awt.Color(255, 255, 255));
        mCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentana(new CompraForm());
            }
        });
        int index = mbMenu.getComponentIndex(jMenu1);
        if (index >= 0) {
            mbMenu.add(mCompras, index);
        } else {
            mbMenu.add(mCompras);
        }
        mbMenu.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mMedicamentos;
    private javax.swing.JMenu mProveedores;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenu mUsuarios;
    private javax.swing.JMenu mVentas;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JDesktopPane pEscritorio;
    // End of variables declaration//GEN-END:variables
}
